#@ load("@ytt:data", "data")

#@ for/end student in data.values.students:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ student.namespace
  labels:
    studentName: #@ student.name
    generated: true
