#@ load("@ytt:data", "data")

#@ def labels():
source: 'carvel-workshop'
generated: true
#@ end

#@ def namespace(name):
apiVersion: v1
kind: Namespace
metadata:
  name: #@ name
  #! Blank line below ignored by YTT

  labels: #@ labels()
#@ end

#@ for/end ns in data.values.namespaces:
--- #@ namespace(ns)
